name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Publish linux-x64
      run: dotnet publish -r linux-x64 -c Release /p:PublishSingleFile=true
    - name: Publish win-x64
      run: dotnet publish -r win-x64 -c Release /p:PublishSingleFile=true
